{
 "title": "FastDFS",
 "description": "Dashboard for FastDFS.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "GroupCount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fastdfs_group_count", "legendFormat": "fastdfs_group_count" }
   ]
  },
  {
   "title": "Active",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fastdfs_active_state", "legendFormat": "fastdfs_active_state" }
   ]
  },
  {
   "title": "WaitSync",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fastdfs_wait_sync_state", "legendFormat": "fastdfs_wait_sync_state" }
   ]
  },
  {
   "title": "Alive",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fastdfs_wait_sync_state{node=\"fastdfs\"} + on(node) fastdfs_active_state{node=\"fastdfs\"}",
     "legendFormat": "alive"
    }
   ]
  }
 ]
}